-- Lanckriet Arena server, D1 schema v1. Safe to run more than once.
CREATE TABLE IF NOT EXISTS players (pid TEXT PRIMARY KEY, name TEXT NOT NULL DEFAULT '', card TEXT NOT NULL DEFAULT '', banned INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS scores (wk TEXT NOT NULL, pid TEXT NOT NULL, metric TEXT NOT NULL, score INTEGER NOT NULL DEFAULT 0, updated INTEGER NOT NULL, PRIMARY KEY (wk, pid));
CREATE INDEX IF NOT EXISTS scores_board ON scores (wk, metric, score DESC);
CREATE TABLE IF NOT EXISTS results (wk TEXT NOT NULL, pid TEXT NOT NULL, metric TEXT NOT NULL, score INTEGER NOT NULL, rank INTEGER NOT NULL, players INTEGER NOT NULL, prize INTEGER NOT NULL DEFAULT 0, claimed INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (wk, pid));
CREATE TABLE IF NOT EXISTS settled (wk TEXT PRIMARY KEY, at INTEGER NOT NULL, players INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS puzzles (id TEXT PRIMARY KEY, route TEXT NOT NULL, status TEXT NOT NULL, fen TEXT NOT NULL, played TEXT NOT NULL, best TEXT NOT NULL, opening TEXT NOT NULL DEFAULT '', elo INTEGER, num INTEGER NOT NULL DEFAULT 1, name TEXT NOT NULL DEFAULT '', pid TEXT NOT NULL, game TEXT NOT NULL DEFAULT '', created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS puzzles_status ON puzzles (status, created DESC);
CREATE INDEX IF NOT EXISTS puzzles_created ON puzzles (created DESC);
CREATE TABLE IF NOT EXISTS quota (pid TEXT NOT NULL, day TEXT NOT NULL, kind TEXT NOT NULL, n INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (pid, day, kind));
CREATE TABLE IF NOT EXISTS activations (hash TEXT NOT NULL, pid TEXT NOT NULL, created INTEGER NOT NULL, last INTEGER NOT NULL, PRIMARY KEY (hash, pid));
CREATE TABLE IF NOT EXISTS ai_usage (day TEXT NOT NULL, pid TEXT NOT NULL, n INTEGER NOT NULL DEFAULT 0, input INTEGER NOT NULL DEFAULT 0, output INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (day, pid));
